### ISSUE TITLE
implement DKIM signature

### ISSUE THREAD

**Issue by pmlopes** [vert-x3/vertx-mail-client#102]
Many mail services verify the host authenticity using DKIM http://www.dkim.org/

As a first iteration step the public key will not be verified to match the configuration private key.

**Comment by gaol** [comment]
I can give it a try if nobody is working on this yet. :)

**Comment by pmlopes** [comment]
Hi @gaol please do! :+1:

**Comment by gaol** [comment]
The RFC document: https://github.com/gaol/vertx-mail-client/wiki/DKIM-Implementation
The feature branch: https://github.com/gaol/vertx-mail-client/tree/dkim-implementation

**Comment by pmlopes** [comment]
Hi @gaol good job. I just have a few suggestions. What about using `vertx-auth-common` to specify how the keys are loaded and doing all crypto. In a way the dataobjects share the same ideas but having just 1 way to do things feels more natural to me.

**Comment by gaol** [comment]
@pmlopes Thanks for the suggestions. :) I agree that is better to organize/maintain the codes. I see a `PubSecKeyOptions` dataobjects in `vertx-auth-common`, but the Public-key sign/verify related codes are located at `Crypto` in `vertx-jwt` component, would you mind to use codes in `vertx-jwt`, or should we move that to `vertx-auth-common` as well ? :)

**Comment by gaol** [comment]
DKIM requires `sha256` and `sha1` to do the hashing, there are only `sha512` implemented in `vertx-auth-common`, I would like to introduce `sha1` and `sha256` to `vertx-auth-common` for that, @pmlopes does it make sense to  you? ;)

**Comment by pmlopes** [comment]
@gaol Adding the missing hashing algorithms should be straighforward to add on auth-common and makes sense. I think we could also propose to move the `Crypto` class to common but it needs to be behind a `@vertxgen` API otherwise it can't be used from other languages/rx/etc...

**Comment by gaol** [comment]
This has many conflicts with PR: https://github.com/vert-x3/vertx-mail-client/pull/108, I will wait that PR got approved for now.

**Comment by gaol** [comment]
PR: #108 has been merged, I resumed working on the feature branch: https://github.com/gaol/vertx-mail-client/tree/dkim-implementation rebased on latest master.
