### ISSUE TITLE
Attachment should accept a ReadStream

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/vertx-mail-client#106]
In order to avoid reading the full content of the attachment in memory, the client should accept ReadStream for attachments.

**Comment by gaol** [comment]
I want to give it a try if no one is working on this yet. :)

**Comment by gaol** [comment]
work in progress at work branch: https://github.com/gaol/vertx-mail-client/tree/ehencement/issue-106

**Comment by gaol** [comment]
@cescoffier @vietj Can anyone review https://github.com/vert-x3/vertx-mail-client/pull/107? Thanks

**Comment by vietj** [comment]
thanks for the contribution @gaol
