### ISSUE TITLE
Changing default "boundary"

### ISSUE THREAD

**Issue by melorbany** [vert-x3/vertx-mail-client#111]
Hello,

I want to change the default boundary in the message mime. I tried to set the Content-Type boundary to custom one but the boundary inside the mime has no change.

    final MultiMap headers = new CaseInsensitiveHeaders();
    headers.set("Content-Type", "multipart/related; boundary=\"=--" + boundary + "\"");

I have checked the source code for MailEncoder and found that the prefix '"=--vertx_mail_"' is fixed inside the code. So what I should do to change the boundary because I don't want to expose that I am using vert.x for sending the email.

Thanks

**Comment by gaol** [comment]
I think we can introduce a boundary prefix in `MailConfig` to accomplish this.

**Comment by gaol** [comment]
I see that  `Message-ID` also has fixed code: `vertxmail`, so introduce a `userAgent` maybe a better approach so that it can be used to generate both boundary and message-id. please see PR: https://github.com/vert-x3/vertx-mail-client/pull/112

**Comment by melorbany** [comment]
@gaol  For Message-ID, you can set it on the message header and you can do the same with In-Reply-To and References. But It didn't work with the boundary.

```java
         MultiMap headers = new CaseInsensitiveHeaders();
         headers.add("Message-ID", messageID);
         headers.add("In-Reply-To", replyID);
         headers.add("References", references);
         message.setHeaders(headers);
````

**Comment by gaol** [comment]
@melorbany Would you please try latest master (4.0.0-SNAPSHOT) ? You can set user agent by:
`MailConfig.setUserAgent("my-mail-user-agent")` to generate a customized boundary.

**Comment by melorbany** [comment]
Thanks @gaol

**Comment by vietj** [comment]
@gaol is this documented ?

**Comment by gaol** [comment]
@vietj If you mean [dataobjects.adoc](https://github.com/vert-x3/vertx-mail-client/blob/master/src/main/asciidoc/dataobjects.adoc#user-content-useragent), yes, it is added there(automatically). :)

If you mean wiki page or website docs, not yet. :)

**Comment by gaol** [comment]
@vietj Sorry for that missing, updated the docs via PR: https://github.com/vert-x3/vertx-mail-client/pull/117

**Comment by vietj** [comment]
thanks @gaol merged
