### ISSUE TITLE
SMTP for outlook not working with versions 3.8.0 and 3.8.1

### ISSUE THREAD

**Issue by jckozy86** [vert-x3/vertx-mail-client#115]
I am trying to send emails through my outlook account using a Java app but i keep getting the following error:

Future{cause=AUTH XOAUTH2 failed 535 5.7.3 Authentication unsuccessful [BN7PR05CA0003.namprd05.prod.outlook.com]}

This worked perfectly in versions 3.7.1 and prior

My settings are:

config = new MailConfig();
config.setHostname("smtp.office365.com");
config.setPort(587);
config.setStarttls(StartTLSOptions.REQUIRED);
config.setUsername(*----*);
config.setPassword(*----*);
config.setAllowRcptErrors(cfg.getEmailConfig().getAllowRcptErrors());
mailClient = MailClient.createShared(vertx, config );

I dont see anything mentioned in the release notes for 3.8.0/1 about mail-client changes...
Either way, is there something i should be adding in my config for this to work?
Is this something known and will be fixed in the upcoming 4.0.0 release?

Using Java 8.222  and Gradle 5.5

**Comment by pmlopes** [comment]
The issue is that Outlook announces that it understand xoauth but the credentials you have are not in that format.

So on the mail config you should specify which algorithms you allow. So it means you need one of these:

 * "DIGEST-MD5",
 * "CRAM-SHA256",
 * "CRAM-SHA1",
 * "CRAM-MD5",
 * "PLAIN",
 * "LOGIN"

**Comment by jckozy86** [comment]
Got it to work by adding login is required, and authMethod=LOGIN

            config = new MailConfig();
            config.setHostname(cfg.getEmailConfig().getHostname());
            config.setPort(cfg.getEmailConfig().getPort());
            config.setStarttls(StartTLSOptions.REQUIRED);
            config.setLogin(LoginOption.REQUIRED);
            config.setAuthMethods("LOGIN");
            config.setUsername(cfg.getEmailConfig().getUsername());
            config.setPassword(cfg.getEmailConfig().getPassword());
            config.setAllowRcptErrors(cfg.getEmailConfig().getAllowRcptErrors());

            mailClient = MailClient.createShared(vertx, config );
