### ISSUE TITLE
From address replaced by bounce address

### ISSUE THREAD

**Issue by counter567** [vert-x3/vertx-mail-client#116]
Hi, I have the problem with the client, that it replaces the from address with the bounce address which is in my opinion wrong.

**Comment by vietj** [comment]
can you provide a reproducer ?

**Comment by counter567** [comment]
I found it in the code:
https://github.com/vert-x3/vertx-mail-client/blob/master/src/main/java/io/vertx/ext/mail/impl/SMTPSendMail.java
```
if (bounceAddr != null && !bounceAddr.isEmpty()) {
        fromAddr = bounceAddr;
      } else {
        fromAddr = email.getFrom();
      }
```

**Comment by gaol** [comment]
@counter567 From https://tools.ietf.org/html/rfc5321#section-3.3 and https://en.wikipedia.org/wiki/Bounce_address, it looks correct to me that when `bounceAddr` is defined, it will be used in the `MAIL FROM` command.

What problems did you get exactly? :) Any errors or misbehavior ?

**Comment by counter567** [comment]
Ok well then you are right. I had the feeling the bounce address was for when you receive an email not delivered notification as it is seperate from the from field in the vertx-mail-client. But then I have to find an other way. Anyway thank you for your time :)
