### ISSUE TITLE
Make the distinction between the resource context and the caller context

### ISSUE THREAD

**Issue by gaol** [vert-x3/vertx-mail-client#125]
Make sure `MailClient.sendMail()` follows Vert.x 4 context model

References:
* https://github.com/vert-x3/wiki/wiki/RFC:-Vert.x-4-context-model
* https://groups.google.com/forum/#!topic/vertx-dev/CA8RzEv28oo

**Comment by vietj** [comment]
Is there a PR for this issue ?

**Comment by gaol** [comment]
Sorry that I was just back from National Holiday, working on it.
