### ISSUE TITLE
Reuse vertx client connection pool 

### ISSUE THREAD

**Issue by gaol** [vert-x3/vertx-mail-client#128]
There is an existing client connection pool implementation in vertx core, we should reuse it for easy maintenance.

~See:  [io.vertx.core.http.impl.pool.Pool](https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/pool/Pool.java)~

See:  [io.vertx.core.net.impl.clientconnection.Pool](https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/net/impl/clientconnection/Pool.java)

And [io.vertx.core.net.impl.clientconnection.ConnectionManager](https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/net/impl/clientconnection/ConnectionManager.java)

**Comment by vietj** [comment]
good idea, it is already used in vertx-redis-client

**Comment by gaol** [comment]
Working on the branch: https://github.com/gaol/vertx-mail-client/tree/issues/128-reuse-vertx-client-conn-pool

Because it has tight relationship with the context issue(#125), I will try to fix both in one PR once it is ready.

**Comment by gaol** [comment]
Resume the work on branch: https://github.com/gaol/vertx-mail-client/pull/new/issues/128-new-conn-pool

**Comment by vietj** [comment]
moving this to 4.1.0 as we want to do some changes to connection pool after 4.0

**Comment by gaol** [comment]
@vietj started working in https://github.com/gaol/vertx-mail-client/tree/new_connpool_from_4.0 based on https://github.com/eclipse-vertx/vert.x/pull/3731

**Comment by vietj** [comment]
@gaol thanks, added to the https://github.com/eclipse-vertx/vert.x/pull/3731 description
