### ISSUE TITLE
Support Pipelining

### ISSUE THREAD

**Issue by gaol** [vert-x3/vertx-mail-client#143]
### Context

[SMTP Pipelining](https://tools.ietf.org/html/rfc2920) is a SMTP extension to save round trips when sending mails.

Most of the SMTP servers support Pipelining now, it would be good if we support this in vertx-mail-client.

**Comment by vietj** [comment]
it would be a great feature indeed.

**Comment by gaol** [comment]
RFC doc: https://github.com/gaol/vertx-mail-client/wiki/Support-Pipelining
Feature branch: https://github.com/gaol/vertx-mail-client/tree/support_pipelining
