### ISSUE TITLE
Format change between Vert.x 3 and 4

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/vertx-mail-client#161]
During the migration between 3 and 4, we found out that the email format changed.

In 3.x, all emails were sent as multipart, regardless if you have attachments.

In 4.x, only emails with attachments are sent as multipart. Without, the emails are sent as simple mail.

While this change make sense, it changes the expectations.

Ideally this new behavior could be toggled using a configuration attribute (defaulting to true, but at least allow the users to roll back to the previous behavior).

**Comment by vietj** [comment]
@gaol can you have a look ?
