### ISSUE TITLE
Vert.x v4 migration: dropping reply arriving after we stopped processing the buffer

### ISSUE THREAD

**Issue by mnylen** [vert-x3/vertx-mail-client#185]
### Version

Which version(s) did you encounter this bug: 4.3.2

### Context

Ever since upgrading from Vert.x v3 to v4, the mail client has started logging these errors:

```
Aug 02, 2022 05:15:09 [vert.x-eventloop-thread-0] ERROR io.vertx.ext.mail.impl.SMTPConnection - dropping reply arriving after we stopped processing the buffer. 
Aug 02, 2022 05:15:09 [vert.x-eventloop-thread-0] ERROR io.vertx.ext.mail.impl.SMTPConnection - socket was closed unexpected. 
```

Using AWS SES SMTP endpoint. The client configuration is as follows:

```
final MailConfig mailConfig = new MailConfig()
  .setHostname(SMTP_HOST)
  .setPort(SMTP_PORT)
  .setStarttls(StartTLSOptions.REQUIRED)
  .setUsername(SMTP_USERNAME)
  .setPassword(SMTP_PASSWORD);

final MailClient client = MailClient.createShared(vertx, mailConfig);
```

Tried setting the keep alive timeout in `MailConfig` to `0` to disable the timeout (it seems this was the behavior in v3), but this did not help. Also tried setting it to `100` (seconds), but this didn't help either.

The issue didn't happen in Vert.x v3.

I've found this post https://groups.google.com/g/vertx/c/pa2XYzhKQ20 discussing the issue, but the suggestions there (changing the keep alive timeout) didn't seem to help.

This doesn't seem severe, as the emails will still get sent. However, would be nice to understand why is this happening.

**Comment by gaol** [comment]
These cases are inevitable, like when connections are idle for a while, the server will close the connections no matter what timeout is set in client side.

It was not showing in `3.x`, because they were logged in `debug` level, `4.x` is using `error` level, I think it is a typo when I did the some changes in SMTPConnection.

I would like to propose to change the log level back to debug to avoid the noise.

**Comment by mnylen** [comment]
Hey! Thanks for the reply. I think using the debug level is a good chance, as it doesn't really seem to cause any issues when it happens.

In the meanwhile, we found out that AWS SES SMTP endpoint looks to have a server-side idle timeout of 10 seconds. Took a lot of effort to figure that out and setting the keep alive timeout to 8 seconds removed most of these from our logs. :)
