### ISSUE TITLE
limit messages count per SMTP connection can send

### ISSUE THREAD

**Issue by NeoCN** [vert-x3/vertx-mail-client#195]
#### Describe the feature

Support control the messages count per SMTP connection can send.  Close the SMTP connection when messages count limit reached.

#### Use cases

From [SendGrid SMTP Rate limits](https://docs.sendgrid.com/for-developers/sending-email/integrating-with-the-smtp-api#rate-limits)

> You may send up to 5k messages per SMTP connection.
> You may open up to 10k concurrent connections from a single server.

**Comment by gaol** [comment]
I think the `maxPoolSize`(defaults to `10`) can be used for the concurrent connections limitation, although you won't get much connections using the shared MailClient.

I will work on the messages count per connection limitation, that should be easy to implement, just wondering how it can be tested.
