### ISSUE TITLE
Unable to close a shared pool in order to create a new one with different config

### ISSUE THREAD

**Issue by KyriacosP** [vert-x3/vertx-mail-client#211]
Hello,

I have a scenario where i have multiple shared clients with different configurations each but under certain conditions the configuration for some of these clients is able to change. As far as i can see there is no way of doing without using the non shared client. The full scenario follows.

I'm using Java 11, Quarkus 2.15.3.Final and i'm getting the Vert.x mail client from the quarkus-mailer extension (vertx-mail-client-4.3.6).

Full Scenario:

A request to send an email comes in, depending on the origin of the request i get the appropriate configuration and create the shared mail client with a unique identifier (the identifier and the configuration are tied to the origin of the request). If this is the first time we have seen this identifier a new pool is created otherwise the refCount in MailHolder is increased by one.

I sent the email but i do not close the mail client after that because if it's a new pool (refCount=1) and you close the client it also closes the underlying pool. Which means that the refCount in MailHolder keeps increasing forever.

I have a way of notifying the service when a configuration change happens for a specific identifier but i cannot find a way to close the pool for that identifier. If i call MailClient.createShared() for that identifier and the call close on the resulting client it just closes the resulting client (Which ends increasing and decreasing respectively the refCount in MailHolder without closing the underlying pool)

P.S.: I'm new to Vert.x and mail client so i might be missing something obvious

Thank you

**Comment by gaol** [comment]
In https://vertx.io/docs/vertx-mail-client/java/, it says:
```
The first call to MailClient.createShared will actually create the pool with the specified config.
Subsequent calls will return a new client instance that uses the same pool,
so the configuration won’t be used
```

and from what I understand, you are trying to create many MailClient instances based on the requests because of different identifier and configurations, I think you need to maintain the instances by yourself, like when a new shared MailClient instance is created, record it in a map using the identifier as the key, and when the configuration is changed, find the MailClient instance by the identifier and close it, which should close the underline pool as well, then create a new one again.

HTH.

**Comment by KyriacosP** [comment]
I see what you mean i will give that a try thank you.

**Comment by KyriacosP** [comment]
Hello again, 
This approach seems to work but i'm a bit worried about concurrent usage of a specific client. Since now we have one client for each identifier how would the mail client handle concurrent usage from two or more different threads?

**Comment by gaol** [comment]
All client instances with the same identifier share the same connection pool, each connection retrieved from the pool is bound to a thread when it gets out from the pool, and the connection won't be reused until it finishes current mail transaction and returns back to the pool. So it shouldn't be an issue with multiple threads, if there is such issue, it is a bug.

**Comment by KyriacosP** [comment]
ok thank you
