### ISSUE TITLE
bare <LF> received after DATA

### ISSUE THREAD

**Issue by cs8898** [vert-x3/vertx-mail-client#219]
When sending Mails with longer Header Values, a "newer" Postfix Server will Reject Mail Submission due to a `bare <LF> received after DATA` Error.

This happens because the Recipient List will be splitted after >=75 chars by just adding a single `\n` instead of `\r\n`.

I Plan to add a PR to correct this behavior.
In the [io.vertx.ext.mail.mailencoder.Utils](https://github.com/vert-x3/vertx-mail-client/blob/master/src/main/java/io/vertx/ext/mail/mailencoder/Utils.java) class are some more places where just a single LineFeed is added.

### Version

Which version(s) did you encounter this bug ?
`3.5.3+`

### Context

[SMTP Smuggling](https://www.postfix.org/smtp-smuggling.html)

### Do you have a reproducer?

Send Mails with a long Subject/Recepient List.

* https://gist.github.com/cs8898/b740ee29206d5b9f7bee7c352d676086

The Gist contains Two Dumps of the RAW SNMP Messages, one from vertx and the other one from Thunderbird.  
Thunderbird encodes all as `\r\n`.

### Relevant class

[io.vertx.ext.mail.mailencoder.Utils](https://github.com/vert-x3/vertx-mail-client/blob/master/src/main/java/io/vertx/ext/mail/mailencoder/Utils.java)

**Comment by Legion2** [comment]
@cs8898 the PR you created does not directly fix the bug here https://github.com/vert-x3/vertx-mail-client/blob/dea280c0ef0e0c3a1ac329c607f2fa5ff2c6fd2a/src/main/java/io/vertx/ext/mail/mailencoder/Utils.java#L155 which should use `\r\n ` instead of `\n ` according to spec. Should I create a PR for this?

**Comment by cs8898** [comment]
Yes thats correct, the encoder only uses \n thats why i only added \r during sending to the SMTP Server.
With adding while encoding all the tests musst bei changed. And it kind of differs the way the MSG Body is handeled.

Just saying that \r\r\n can also lead to problems. But Sendmail does not tackle these.

Could be an aspect to discuss.

**Comment by Legion2** [comment]
Adding /r afterwards to all headers seems like a workaround. Which is not necessary for this particular problem I'm facing, because we can just fix the header encoding to be according to the specification.

**Comment by cs8898** [comment]
Can you reference the specs and relevant chapter here, what specs are you refering to? Jakarta Mail?

I can tackle the necessary changes next week.

**Comment by Legion2** [comment]
I refer to this RFC https://datatracker.ietf.org/doc/html/rfc2047#section-2
> An 'encoded-word' may not be more than 75 characters long, including  'charset', 'encoding', 'encoded-text', and delimiters. If it is desirable to encode more text than will fit in an 'encoded-word' of 75 characters, multiple 'encoded-word's (separated by CRLF SPACE) may be used.

**Comment by Legion2** [comment]
@cs8898 had you time to look at this?

**Comment by cs8898** [comment]
Hi sorry, was lacking of time for that. I try to schedule it for that weekend.

I'm currently using the exclude for my server
https://www.postfix.org/postconf.5.html#smtpd_forbid_bare_newline_exclusions

**Comment by cs8898** [comment]
@Legion2 have a look at #221

**Comment by cs8898** [comment]
@vietj is @alexlehm still the maintainer of the smtp client?
Will anyone from the "core" maintainers give us some feedback on that issue.

At least for users not having the possibility to modify their postfix configs, as its the case when you use hosted services...

**Comment by gaol** [comment]
@cs8898 sorry for late response. I will check the pr this week.
