### ISSUE TITLE
allow empty address, this can be used as sender (<>)

### ISSUE THREAD

**Issue by alexlehm** [vert-x3/vertx-mail-client#28]
this is allowed in smtp as the local mailer-daemon address of the sending server

**Comment by purplefox** [comment]
Hi Alex, no need to put "TODO" in the title of the issues. If it's an issue it's already implicitly TODO :)

**Comment by alexlehm** [comment]
I matched the TODO comments with the issues, the title should probably read "TODO in File.java": xxx

**Comment by alexlehm** [comment]
but i can probably rename them when the issue is done

**Comment by alexlehm** [comment]
fixed with commit 782437e066ec838c3b3f7f31de936b94c71ef106
empty is address is allowed
