### ISSUE TITLE
Would be nice if MailConfig used defaults for "missing" options

### ISSUE THREAD

**Issue by sfitts** [vert-x3/vertx-mail-client#54]
If you create a MailConfig using a JsonObject then any option that is missing gets set to null instead of it's default value.  This differs from the pattern used in most other Vert.x components where any missing value will be assigned the default (see for example VertxOptions or HttpServerOptions).

**Comment by alexlehm** [comment]
I figured i should make the json toString result as short as possible by leaving out the keys with default values, if that is done differently in other modules it certainly makes sense to do it the same way.

**Comment by cescoffier** [comment]
`starttls` and `login` should use the default value is not set in the json string (if someone creates the json string by himself).

In 3.3.0, we should probably remove the JSON serialization to use converters, but this could be a breaking change, that's why I don't use them right now.

**Comment by sfitts** [comment]
Fair enough.  As a user I was just observing that the behavior difference caught me by surprise (I assumed it worked like all the other cases).

**Comment by cescoffier** [comment]
@sfitts - I've proposed a PR fixing it.

**Comment by sfitts** [comment]
Sorry missed that.  Looks good.
