### ISSUE TITLE
inline attachment for sending inline images

### ISSUE THREAD

**Issue by alexlehm** [vert-x3/vertx-mail-client#59]
this should probably be a bit more general, adding headers to attachments is necessary and creating nested multipart messages might make sense for other usecases as well.

**Comment by alexlehm** [comment]
implemented as branch issues/#59-inline-images 0435d3ca8a2bb287a8098cc2db0867341d242f19

**Comment by remi128** [comment]
cooooool - just saw that you merged it

**Comment by alexlehm** [comment]
@remi128 please check if it works for you

**Comment by remi128** [comment]
no, unfortunately not. A quick view showed me, that the multipart/ related is not defined. I used SNAPSHOT-3.3.0

**Comment by alexlehm** [comment]
unless I have messed up the merge process, it should create the multipart/related structure when setInlineAttachment is used https://github.com/vert-x3/vertx-mail-client/blob/e42da943604ae252089afac1b20e16543e140857/vertx-mail-client/src/main/java/io/vertx/ext/mail/mailencoder/MailEncoder.java#L118

**Comment by remi128** [comment]
yes, you multipart related is in, but unfortunately its not enough. In Mail / Thunderbird on OSX its still displaying it like attachment. I fetched out my implementation to compare the results. 
In your solution you are writing the multipart related directly:

```
Content-Type: multipart/related; boundary="=--vertx_mail_1239759990_1460112707511_0"

--=--vertx_mail_1239759990_1460112707511_0
Content-Type: text/html
Content-Transfer-Encoding: 7bit

this is html text <a href="braintags.de">braintags.de</a> with an <img src="cid:0.1460112690182@localhost"/>

--=--vertx_mail_1239759990_1460112707511_0
Content-Type: image/png; name=0.1460112690182@localhost
Content-Transfer-Encoding: base64
Content-Disposition: inline; filename=0.1460112690182@localhost

iVBORw0KGgoAAAANSUhEUgAAALkAAABGCAYAAACQaTWQAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJ
```
in "my" solution first the multipart/mixed is written, which then integrates the multipart/related

```
Content-Type: multipart/mixed; boundary="=--vertx_mail_1301664418_1460112915299_0"

--=--vertx_mail_1301664418_1460112915299_0
Content-Type: multipart/related; boundary="=--vertx_mail_1301664418_1460112915299_1"

--=--vertx_mail_1301664418_1460112915299_1
Content-Type: text/html
Content-Transfer-Encoding: 7bit

this is html text <a href="braintags.de">braintags.de</a> with an <img src="cid:0.1460112914924@localhost"/>

--=--vertx_mail_1301664418_1460112915299_1
Content-Type: image/png; name=0.1460112914924@localhost
Content-Transfer-Encoding: base64
Content-Disposition: inline; filename=0.1460112914924@localhost
Content-ID: <0.1460112914924@localhost>

iVBORw0KGgoAAAANSUhEUgAAALkAAABGCAYAAACQaTWQAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJ
```

**Comment by alexlehm** [comment]
@remi128 Michael, I think you are missing the Content-ID in the image but I am not completely sure

will do some more tests

**Comment by remi128** [comment]
@alexlehm Hey Alex,
if you like to look, my unit test is  [here](https://github.com/BraintagsGmbH/NetRelay-Controller/blob/master/src/test/java/de/braintags/netrelay/unit/TMailController.java), it is the test sendHtmlMessageWithInlineImage. The execution of mail sending is under [MailController](https://github.com/BraintagsGmbH/NetRelay-Controller/blob/master/src/main/java/de/braintags/netrelay/controller/api/MailController.java), the responsible method is parseInlineMessage

**Comment by alexlehm** [comment]
The method createAttachment is not setting the Content-ID header, then I assume the mail client will not find the correct attachment for each image. Could please try this change: https://github.com/BraintagsGmbH/NetRelay-Controller/pull/1, I assume that should fix it.

Setting the Content-ID is a bit cumbersome since it is not a property currently, we could add that one

**Comment by remi128** [comment]
yes - that was it - thank you
