### ISSUE TITLE
remove left over idle connection handling

### ISSUE THREAD

**Issue by alexlehm** [vert-x3/vertx-mail-client#70]
before 3.0 I started an implementation of idle smtp connections that could be reused for a specified time (e.g. 5 minutes), this option was removed for the 3.0 version, but the status of idle connection is still checked

**Comment by alexlehm** [comment]
Will probably not finish that for 3.4

**Comment by vietj** [comment]
can we reuse vertx client connection pool and remove the custom one in vertx-mail-client ?

**Comment by gaol** [comment]
@vietj Do you mean the [io.vertx.core.http.impl.pool.Pool](https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/pool/Pool.java) ?

**Comment by gaol** [comment]
I think it should be, created https://github.com/vert-x3/vertx-mail-client/issues/128 to track the changes.

**Comment by vietj** [comment]
I think it would make sense to reuse the existing common pool from vertx-core indeed

**Comment by gaol** [comment]
vertx-mail-client is using new connection pool in vertx-core from 4.1.0, I am closing this one.
