### ISSUE TITLE
Oauth authentication

### ISSUE THREAD

**Issue by alexlehm** [vert-x3/vertx-mail-client#80]
When using gmail, it is currently necessary to switch to old auth support since the mail client does not support oauth authentication (e.g. thunderbird supports that)

If that is possible, supporting oauth would be good.

**Comment by pmlopes** [comment]
What are the requirements for Gmail? Could https://github.com/vert-x3/vertx-auth/issues/88 solve it for you? I think that that's the reason Google has this, server to server authz but I'm not familiar with Gmail internals

**Comment by alexlehm** [comment]
I have to check how the gmail auth works

**Comment by pmlopes** [comment]
https://github.com/vert-x3/vertx-auth/pull/106 implements Google OAuth2 server to server authZ maybe it could work for you. I guess that if you create a provider for server to server and ask for a token see example: https://github.com/vert-x3/vertx-auth/blob/7dae48a809f6eea3f29a856a6035bc866ebd3c97/vertx-auth-oauth2/src/test/java/io/vertx/ext/auth/test/oauth2/OAuth2AuthJWTTest.java

Then you could use SASL auth which basically is:

```java
oauth2.getToken(jwt, res -> {
      if (res.failed()) {
        fail(res.cause());
      } else {
        AccessToken token = res.result();
        // XOAUTH2
        String user = base64(
          "user=" + user + 
          "\1auth=Bearer " + token.principal().getString("access_token") + "\1\1");
        ...
      }
});

**Comment by ashertarno** [comment]
hey @alexlehm , did you find a way to work with gmail using oauth2?
i understand @pmlopes ' solution, but it's not clear if there is anything we can do with the token in vertx-mail client as the latest expects to receive username and password.

**Comment by alexlehm** [comment]
I didn't get this to work yet properly. I can create oauth tokens and insert them into the smtp auth protocol by adding a authentication method. For that to work without patching the class https://github.com/vert-x3/vertx-mail-client/blob/master/vertx-mail-client/src/main/java/io/vertx/ext/mail/impl/sasl/AuthOperationFactory.java which is currently private, it would be necessary for the list of auth classes to be extensible.

**Comment by vietj** [comment]
@pmlopes can we open an issue in vertx-auth to make progress on this ?
