### ISSUE TITLE
attachment filenames with non US-ASCII characters are garbled

### ISSUE THREAD

**Issue by DaC1989** [vert-x3/vertx-mail-client#82]
sorry for my poor english.
when I send attachment with a chinese name, it would be Garbled.
so I use javax.mail.internet.MimeUtility.encodeText("你好").
then it worked.
maybe we shoud add it into vertx-mail-client?
or, there is another way which I don't known.
Look forward to your reply, thanks

**Comment by alexlehm** [comment]
I have done some testing with non-ascii chars, but may have missed some cases where encoding is required. I will try to write a unit test for that and implement a fix.

**Comment by alexlehm** [comment]
ok, i can confirm that we are missing the encoding for filenames

**Comment by DaC1989** [comment]
thanks

**Comment by alexlehm** [comment]
@DaC1989 not fixed yet, i will do it tonight

**Comment by alexlehm** [comment]
fixed with https://github.com/vert-x3/vertx-mail-client/pull/83
added filename encoding and changed the filename to be enclosed in quotes

**Comment by alexlehm** [comment]
@DaC1989 fix is in 3.4.0-SNAPSHOT if you want to give it a try

**Comment by DaC1989** [comment]
ok, thank you very much
