### ISSUE TITLE
Intermittend failure in MailClientImpl2Test#testCloseWhileMailActive

### ISSUE THREAD

**Issue by alexlehm** [vert-x3/vertx-mail-client#92]
The CI test on Jenkins fails sometimes in the test MailClientImpl2Test#testCloseWhileMailActive, e.g. in this build https://vertx.ci.cloudbees.com/job/vert.x3-mail-client/2037/console
this is probably a timing issue as the test tries to wait in two intervals to catch the state of the connection pool, maybe this test does not make much sense after all

**Comment by gaol** [comment]
I don't see this failure for quit long time, I am closing it.
